# Generated by Django 4.2.1 on 2023-06-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_user_avatar_alter_user_bio_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatar.svg", null=True, upload_to="images"
            ),
        ),
    ]
